// Design tokens for Sprout. Translated from mockups/06-style-guide.html.
// This TS object is the source of truth; tokens.css is a derived artifact
// generated by scripts/build-css-vars.ts.

export const color = {
  forest: {
    900: '#0f2419',
    800: '#163528',
    700: '#1c4232',
    600: '#245440',
    500: '#2f6a52',
    300: '#6ea88f',
    200: '#a8d5b8',
    100: '#d3e6dc',
  },
  tomato: {
    700: '#b8351f',
    500: '#e2553a',
    300: '#f49077',
    100: '#fbe0d6',
  },
  water: {
    500: '#3d7da3',
    300: '#79b6d6',
    100: '#dceaf6',
  },
  soil: {
    500: '#a87838',
    300: '#d4a96a',
    100: '#ecdcc7',
  },
  peach: {
    200: '#fbdcb4',
    100: '#fdebd3',
    50: '#fff5e4',
  },
  cream: '#fff8ee',
  bone: '#fefaf2',
  paper: '#fdf5e7',
  ink: '#1a2b25',
  inkSoft: '#4d5e57',
  inkMute: '#8a978f',
} as const;

export const space = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 18,
  lg: 24,
  xl: 36,
  '2xl': 48,
  '3xl': 64,
} as const;

export const radius = {
  xs: 6,
  sm: 10,
  md: 18,
  lg: 28,
  xl: 36,
  full: 999,
} as const;

export const shadow = {
  sm: '0 1px 2px rgba(0, 0, 0, 0.18), 0 2px 8px rgba(0, 0, 0, 0.12)',
  md: '0 8px 22px rgba(0, 0, 0, 0.22), 0 2px 6px rgba(0, 0, 0, 0.12)',
  lg: '0 22px 50px rgba(0, 0, 0, 0.30), 0 6px 14px rgba(0, 0, 0, 0.14)',
} as const;

export const fontFamily = {
  display: '"Fraunces", serif',
  body: '"Inter", system-ui, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

export const type = {
  display: { size: 78, lineHeight: 0.92, weight: 500 },
  h1: { size: 56, lineHeight: 1.0, weight: 500 },
  h2: { size: 40, lineHeight: 1.0, weight: 500 },
  h3: { size: 22, lineHeight: 1.15, weight: 500 },
  bodyL: { size: 16, lineHeight: 1.55, weight: 400 },
  bodyM: { size: 14, lineHeight: 1.5, weight: 400 },
  bodyS: { size: 13, lineHeight: 1.5, weight: 400 },
  caption: { size: 11.5, lineHeight: 1.4, weight: 700 },
} as const;

export const tokens = {
  color,
  space,
  radius,
  shadow,
  fontFamily,
  type,
} as const;

export type Tokens = typeof tokens;
export default tokens;
