// Generates packages/shared/dist/tokens.css from src/tokens.ts.
// Run via `pnpm --filter @sprout/shared build:css`. Apps wire this as a
// `prebuild` / `predev` step so every web build has fresh CSS variables.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import tokens, { color, space, radius, shadow, fontFamily } from '../src/tokens.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '..', 'dist', 'tokens.css');

const indent = '  ';
const lines: string[] = [];

const pushColors = (group: string, value: unknown): void => {
  if (typeof value === 'string') {
    lines.push(`${indent}--color-${group}: ${value};`);
    return;
  }
  if (value && typeof value === 'object') {
    for (const [step, hex] of Object.entries(value as Record<string, string>)) {
      lines.push(`${indent}--color-${group}-${step}: ${hex};`);
    }
  }
};

lines.push('/* Generated by packages/shared/scripts/build-css-vars.ts. Do not edit. */');
lines.push(':root {');

for (const [group, value] of Object.entries(color)) {
  pushColors(kebab(group), value);
}

for (const [name, px] of Object.entries(space)) {
  lines.push(`${indent}--space-${name}: ${px}px;`);
}

for (const [name, px] of Object.entries(radius)) {
  if (name === 'full') {
    lines.push(`${indent}--radius-full: 999px;`);
  } else {
    lines.push(`${indent}--radius-${name}: ${px}px;`);
  }
}

for (const [name, value] of Object.entries(shadow)) {
  lines.push(`${indent}--shadow-${name}: ${value};`);
}

for (const [name, value] of Object.entries(fontFamily)) {
  lines.push(`${indent}--font-${name}: ${value};`);
}

lines.push('}');
lines.push('');

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join('\n'), 'utf8');

console.log(`Wrote ${outFile} (${Object.keys(tokens).length} token groups).`);

function kebab(input: string): string {
  return input.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}
